import os
from typing import Tuple, Any
from dotenv import load_dotenv
from langgraph.graph import END, StateGraph
from langchain_community.vectorstores import Chroma
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import  EmbeddingsFilter
from langchain.retrievers.document_compressors import DocumentCompressorPipeline
from langchain_community.document_transformers import EmbeddingsRedundantFilter
from langchain_text_splitters import CharacterTextSplitter
import json
from langchain_community.document_loaders import PyPDFLoader
import chromadb
from langchain_openai import OpenAIEmbeddings
from typing_extensions import TypedDict
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI